version: "3.8"

services:
  localstack-full:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_full_main}"
    image: localstack/localstack-full:0.12.19.1
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"      
    environment:
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock      
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp
      - DEFAULT_REGION=us-east-1
      - EXTRA_CORS_ALLOWED_ORIGINS=app://.
      - DISABLE_CORS_CHECKS=1
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
